// Periodic table data for elements 1-92.
// Fields:
//   name           : English name
//   symbol         : Chemical symbol
//   atomicNumber   : Z
//   atomicMass     : standard atomic weight (u)
//   group          : IUPAC group 1-18; lanthanides assigned synthetic group 3
//   period         : 1-7
//   discoveryYear  : integer year; ANCIENT_YEAR sentinel for prehistoric elements
//   state          : 'solid' | 'liquid' | 'gas' at 25 C / 1 atm
//
// Discovery year of "ancient" elements (known since prehistory) is set to
// ANCIENT_YEAR so numeric comparisons still work; the UI displays "Ancient".
const ANCIENT_YEAR = -3000;

const ELEMENTS = [
    { name: "Hydrogen",     symbol: "H",  atomicNumber: 1,  atomicMass: 1.008,   group: 1,  period: 1, discoveryYear: 1766, state: "gas"   },
    { name: "Helium",       symbol: "He", atomicNumber: 2,  atomicMass: 4.0026,  group: 18, period: 1, discoveryYear: 1868, state: "gas"   },
    { name: "Lithium",      symbol: "Li", atomicNumber: 3,  atomicMass: 6.94,    group: 1,  period: 2, discoveryYear: 1817, state: "solid" },
    { name: "Beryllium",    symbol: "Be", atomicNumber: 4,  atomicMass: 9.0122,  group: 2,  period: 2, discoveryYear: 1798, state: "solid" },
    { name: "Boron",        symbol: "B",  atomicNumber: 5,  atomicMass: 10.81,   group: 13, period: 2, discoveryYear: 1808, state: "solid" },
    { name: "Carbon",       symbol: "C",  atomicNumber: 6,  atomicMass: 12.011,  group: 14, period: 2, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Nitrogen",     symbol: "N",  atomicNumber: 7,  atomicMass: 14.007,  group: 15, period: 2, discoveryYear: 1772, state: "gas"   },
    { name: "Oxygen",       symbol: "O",  atomicNumber: 8,  atomicMass: 15.999,  group: 16, period: 2, discoveryYear: 1774, state: "gas"   },
    { name: "Fluorine",     symbol: "F",  atomicNumber: 9,  atomicMass: 18.998,  group: 17, period: 2, discoveryYear: 1886, state: "gas"   },
    { name: "Neon",         symbol: "Ne", atomicNumber: 10, atomicMass: 20.180,  group: 18, period: 2, discoveryYear: 1898, state: "gas"   },
    { name: "Sodium",       symbol: "Na", atomicNumber: 11, atomicMass: 22.990,  group: 1,  period: 3, discoveryYear: 1807, state: "solid" },
    { name: "Magnesium",    symbol: "Mg", atomicNumber: 12, atomicMass: 24.305,  group: 2,  period: 3, discoveryYear: 1755, state: "solid" },
    { name: "Aluminium",    symbol: "Al", atomicNumber: 13, atomicMass: 26.982,  group: 13, period: 3, discoveryYear: 1825, state: "solid" },
    { name: "Silicon",      symbol: "Si", atomicNumber: 14, atomicMass: 28.085,  group: 14, period: 3, discoveryYear: 1824, state: "solid" },
    { name: "Phosphorus",   symbol: "P",  atomicNumber: 15, atomicMass: 30.974,  group: 15, period: 3, discoveryYear: 1669, state: "solid" },
    { name: "Sulfur",       symbol: "S",  atomicNumber: 16, atomicMass: 32.06,   group: 16, period: 3, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Chlorine",     symbol: "Cl", atomicNumber: 17, atomicMass: 35.45,   group: 17, period: 3, discoveryYear: 1774, state: "gas"   },
    { name: "Argon",        symbol: "Ar", atomicNumber: 18, atomicMass: 39.948,  group: 18, period: 3, discoveryYear: 1894, state: "gas"   },
    { name: "Potassium",    symbol: "K",  atomicNumber: 19, atomicMass: 39.098,  group: 1,  period: 4, discoveryYear: 1807, state: "solid" },
    { name: "Calcium",      symbol: "Ca", atomicNumber: 20, atomicMass: 40.078,  group: 2,  period: 4, discoveryYear: 1808, state: "solid" },
    { name: "Scandium",     symbol: "Sc", atomicNumber: 21, atomicMass: 44.956,  group: 3,  period: 4, discoveryYear: 1879, state: "solid" },
    { name: "Titanium",     symbol: "Ti", atomicNumber: 22, atomicMass: 47.867,  group: 4,  period: 4, discoveryYear: 1791, state: "solid" },
    { name: "Vanadium",     symbol: "V",  atomicNumber: 23, atomicMass: 50.942,  group: 5,  period: 4, discoveryYear: 1801, state: "solid" },
    { name: "Chromium",     symbol: "Cr", atomicNumber: 24, atomicMass: 51.996,  group: 6,  period: 4, discoveryYear: 1797, state: "solid" },
    { name: "Manganese",    symbol: "Mn", atomicNumber: 25, atomicMass: 54.938,  group: 7,  period: 4, discoveryYear: 1774, state: "solid" },
    { name: "Iron",         symbol: "Fe", atomicNumber: 26, atomicMass: 55.845,  group: 8,  period: 4, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Cobalt",       symbol: "Co", atomicNumber: 27, atomicMass: 58.933,  group: 9,  period: 4, discoveryYear: 1735, state: "solid" },
    { name: "Nickel",       symbol: "Ni", atomicNumber: 28, atomicMass: 58.693,  group: 10, period: 4, discoveryYear: 1751, state: "solid" },
    { name: "Copper",       symbol: "Cu", atomicNumber: 29, atomicMass: 63.546,  group: 11, period: 4, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Zinc",         symbol: "Zn", atomicNumber: 30, atomicMass: 65.38,   group: 12, period: 4, discoveryYear: 1746, state: "solid" },
    { name: "Gallium",      symbol: "Ga", atomicNumber: 31, atomicMass: 69.723,  group: 13, period: 4, discoveryYear: 1875, state: "solid" },
    { name: "Germanium",    symbol: "Ge", atomicNumber: 32, atomicMass: 72.630,  group: 14, period: 4, discoveryYear: 1886, state: "solid" },
    { name: "Arsenic",      symbol: "As", atomicNumber: 33, atomicMass: 74.922,  group: 15, period: 4, discoveryYear: 1250, state: "solid" },
    { name: "Selenium",     symbol: "Se", atomicNumber: 34, atomicMass: 78.971,  group: 16, period: 4, discoveryYear: 1817, state: "solid" },
    { name: "Bromine",      symbol: "Br", atomicNumber: 35, atomicMass: 79.904,  group: 17, period: 4, discoveryYear: 1826, state: "liquid"},
    { name: "Krypton",      symbol: "Kr", atomicNumber: 36, atomicMass: 83.798,  group: 18, period: 4, discoveryYear: 1898, state: "gas"   },
    { name: "Rubidium",     symbol: "Rb", atomicNumber: 37, atomicMass: 85.468,  group: 1,  period: 5, discoveryYear: 1861, state: "solid" },
    { name: "Strontium",    symbol: "Sr", atomicNumber: 38, atomicMass: 87.62,   group: 2,  period: 5, discoveryYear: 1790, state: "solid" },
    { name: "Yttrium",      symbol: "Y",  atomicNumber: 39, atomicMass: 88.906,  group: 3,  period: 5, discoveryYear: 1794, state: "solid" },
    { name: "Zirconium",    symbol: "Zr", atomicNumber: 40, atomicMass: 91.224,  group: 4,  period: 5, discoveryYear: 1789, state: "solid" },
    { name: "Niobium",      symbol: "Nb", atomicNumber: 41, atomicMass: 92.906,  group: 5,  period: 5, discoveryYear: 1801, state: "solid" },
    { name: "Molybdenum",   symbol: "Mo", atomicNumber: 42, atomicMass: 95.95,   group: 6,  period: 5, discoveryYear: 1778, state: "solid" },
    { name: "Technetium",   symbol: "Tc", atomicNumber: 43, atomicMass: 98,      group: 7,  period: 5, discoveryYear: 1937, state: "solid" },
    { name: "Ruthenium",    symbol: "Ru", atomicNumber: 44, atomicMass: 101.07,  group: 8,  period: 5, discoveryYear: 1844, state: "solid" },
    { name: "Rhodium",      symbol: "Rh", atomicNumber: 45, atomicMass: 102.91,  group: 9,  period: 5, discoveryYear: 1803, state: "solid" },
    { name: "Palladium",    symbol: "Pd", atomicNumber: 46, atomicMass: 106.42,  group: 10, period: 5, discoveryYear: 1803, state: "solid" },
    { name: "Silver",       symbol: "Ag", atomicNumber: 47, atomicMass: 107.87,  group: 11, period: 5, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Cadmium",      symbol: "Cd", atomicNumber: 48, atomicMass: 112.41,  group: 12, period: 5, discoveryYear: 1817, state: "solid" },
    { name: "Indium",       symbol: "In", atomicNumber: 49, atomicMass: 114.82,  group: 13, period: 5, discoveryYear: 1863, state: "solid" },
    { name: "Tin",          symbol: "Sn", atomicNumber: 50, atomicMass: 118.71,  group: 14, period: 5, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Antimony",     symbol: "Sb", atomicNumber: 51, atomicMass: 121.76,  group: 15, period: 5, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Tellurium",    symbol: "Te", atomicNumber: 52, atomicMass: 127.60,  group: 16, period: 5, discoveryYear: 1782, state: "solid" },
    { name: "Iodine",       symbol: "I",  atomicNumber: 53, atomicMass: 126.90,  group: 17, period: 5, discoveryYear: 1811, state: "solid" },
    { name: "Xenon",        symbol: "Xe", atomicNumber: 54, atomicMass: 131.29,  group: 18, period: 5, discoveryYear: 1898, state: "gas"   },
    { name: "Caesium",      symbol: "Cs", atomicNumber: 55, atomicMass: 132.91,  group: 1,  period: 6, discoveryYear: 1860, state: "solid" },
    { name: "Barium",       symbol: "Ba", atomicNumber: 56, atomicMass: 137.33,  group: 2,  period: 6, discoveryYear: 1808, state: "solid" },
    // Lanthanides: assigned synthetic group 3 for comparison purposes
    { name: "Lanthanum",    symbol: "La", atomicNumber: 57, atomicMass: 138.91,  group: 3,  period: 6, discoveryYear: 1839, state: "solid" },
    { name: "Cerium",       symbol: "Ce", atomicNumber: 58, atomicMass: 140.12,  group: 3,  period: 6, discoveryYear: 1803, state: "solid" },
    { name: "Praseodymium", symbol: "Pr", atomicNumber: 59, atomicMass: 140.91,  group: 3,  period: 6, discoveryYear: 1885, state: "solid" },
    { name: "Neodymium",    symbol: "Nd", atomicNumber: 60, atomicMass: 144.24,  group: 3,  period: 6, discoveryYear: 1885, state: "solid" },
    { name: "Promethium",   symbol: "Pm", atomicNumber: 61, atomicMass: 145,     group: 3,  period: 6, discoveryYear: 1945, state: "solid" },
    { name: "Samarium",     symbol: "Sm", atomicNumber: 62, atomicMass: 150.36,  group: 3,  period: 6, discoveryYear: 1879, state: "solid" },
    { name: "Europium",     symbol: "Eu", atomicNumber: 63, atomicMass: 151.96,  group: 3,  period: 6, discoveryYear: 1901, state: "solid" },
    { name: "Gadolinium",   symbol: "Gd", atomicNumber: 64, atomicMass: 157.25,  group: 3,  period: 6, discoveryYear: 1880, state: "solid" },
    { name: "Terbium",      symbol: "Tb", atomicNumber: 65, atomicMass: 158.93,  group: 3,  period: 6, discoveryYear: 1843, state: "solid" },
    { name: "Dysprosium",   symbol: "Dy", atomicNumber: 66, atomicMass: 162.50,  group: 3,  period: 6, discoveryYear: 1886, state: "solid" },
    { name: "Holmium",      symbol: "Ho", atomicNumber: 67, atomicMass: 164.93,  group: 3,  period: 6, discoveryYear: 1878, state: "solid" },
    { name: "Erbium",       symbol: "Er", atomicNumber: 68, atomicMass: 167.26,  group: 3,  period: 6, discoveryYear: 1843, state: "solid" },
    { name: "Thulium",      symbol: "Tm", atomicNumber: 69, atomicMass: 168.93,  group: 3,  period: 6, discoveryYear: 1879, state: "solid" },
    { name: "Ytterbium",    symbol: "Yb", atomicNumber: 70, atomicMass: 173.05,  group: 3,  period: 6, discoveryYear: 1878, state: "solid" },
    { name: "Lutetium",     symbol: "Lu", atomicNumber: 71, atomicMass: 174.97,  group: 3,  period: 6, discoveryYear: 1907, state: "solid" },
    { name: "Hafnium",      symbol: "Hf", atomicNumber: 72, atomicMass: 178.49,  group: 4,  period: 6, discoveryYear: 1923, state: "solid" },
    { name: "Tantalum",     symbol: "Ta", atomicNumber: 73, atomicMass: 180.95,  group: 5,  period: 6, discoveryYear: 1802, state: "solid" },
    { name: "Tungsten",     symbol: "W",  atomicNumber: 74, atomicMass: 183.84,  group: 6,  period: 6, discoveryYear: 1783, state: "solid" },
    { name: "Rhenium",      symbol: "Re", atomicNumber: 75, atomicMass: 186.21,  group: 7,  period: 6, discoveryYear: 1925, state: "solid" },
    { name: "Osmium",       symbol: "Os", atomicNumber: 76, atomicMass: 190.23,  group: 8,  period: 6, discoveryYear: 1803, state: "solid" },
    { name: "Iridium",      symbol: "Ir", atomicNumber: 77, atomicMass: 192.22,  group: 9,  period: 6, discoveryYear: 1803, state: "solid" },
    { name: "Platinum",     symbol: "Pt", atomicNumber: 78, atomicMass: 195.08,  group: 10, period: 6, discoveryYear: 1735, state: "solid" },
    { name: "Gold",         symbol: "Au", atomicNumber: 79, atomicMass: 196.97,  group: 11, period: 6, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Mercury",      symbol: "Hg", atomicNumber: 80, atomicMass: 200.59,  group: 12, period: 6, discoveryYear: ANCIENT_YEAR, state: "liquid"},
    { name: "Thallium",     symbol: "Tl", atomicNumber: 81, atomicMass: 204.38,  group: 13, period: 6, discoveryYear: 1861, state: "solid" },
    { name: "Lead",         symbol: "Pb", atomicNumber: 82, atomicMass: 207.2,   group: 14, period: 6, discoveryYear: ANCIENT_YEAR, state: "solid" },
    { name: "Bismuth",      symbol: "Bi", atomicNumber: 83, atomicMass: 208.98,  group: 15, period: 6, discoveryYear: 1753, state: "solid" },
    { name: "Polonium",     symbol: "Po", atomicNumber: 84, atomicMass: 209,     group: 16, period: 6, discoveryYear: 1898, state: "solid" },
    { name: "Astatine",     symbol: "At", atomicNumber: 85, atomicMass: 210,     group: 17, period: 6, discoveryYear: 1940, state: "solid" },
    { name: "Radon",        symbol: "Rn", atomicNumber: 86, atomicMass: 222,     group: 18, period: 6, discoveryYear: 1900, state: "gas"   },
    { name: "Francium",     symbol: "Fr", atomicNumber: 87, atomicMass: 223,     group: 1,  period: 7, discoveryYear: 1939, state: "solid" },
    { name: "Radium",       symbol: "Ra", atomicNumber: 88, atomicMass: 226,     group: 2,  period: 7, discoveryYear: 1898, state: "solid" },
    // Actinides up to U: assigned synthetic group 3
    { name: "Actinium",     symbol: "Ac", atomicNumber: 89, atomicMass: 227,     group: 3,  period: 7, discoveryYear: 1899, state: "solid" },
    { name: "Thorium",      symbol: "Th", atomicNumber: 90, atomicMass: 232.04,  group: 3,  period: 7, discoveryYear: 1829, state: "solid" },
    { name: "Protactinium", symbol: "Pa", atomicNumber: 91, atomicMass: 231.04,  group: 3,  period: 7, discoveryYear: 1913, state: "solid" },
    { name: "Uranium",      symbol: "U",  atomicNumber: 92, atomicMass: 238.03,  group: 3,  period: 7, discoveryYear: 1789, state: "solid" },
];
